# Site settings
title: Victor Sandu
description: Business Technoloy Management Student and Athlete
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Victor Sandu
user_description: Thanks for visiting! I'm Victor and I am an aspiring developer currently studying Business Technology Management at Ryerson University. When I'm not studying or coding, I'm training for triathlons and I competed for Team Canada in the 2019 ITU World Champs. Feel free to scroll through to learn more about me!
user_title: Student Athlete
email: vsandu@ryerson.ca
#twitter_username: lorem_ipsum
github_username:  victorsandu
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
